"""Add institutional governance fields

Revision ID: 1a6510b47dd9
Revises: 7f9633e90c49
Create Date: 2026-05-13 18:16:39.051373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1a6510b47dd9'
down_revision: Union[str, None] = '7f9633e90c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('attempts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('attempts', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('attempts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_attempts_is_deleted'), 'attempts', ['is_deleted'], unique=False)
    op.drop_column('job_execution_registry', 'created_at')
    op.drop_column('learning_interventions', 'reliability_snapshot')
    op.drop_column('learning_interventions', 'updated_at')
    op.drop_column('learning_interventions', 'metric_version')
    op.drop_column('learning_interventions', 'generated_at')
    op.add_column('reports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reports_is_deleted'), 'reports', ['is_deleted'], unique=False)
    op.add_column('tests', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'created_at')
    op.drop_index(op.f('ix_reports_is_deleted'), table_name='reports')
    op.drop_column('reports', 'deleted_at')
    op.drop_column('reports', 'is_deleted')
    op.drop_column('reports', 'updated_by')
    op.drop_column('reports', 'created_by')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'created_at')
    op.add_column('learning_interventions', sa.Column('generated_at', sa.DATETIME(), nullable=False))
    op.add_column('learning_interventions', sa.Column('metric_version', sa.VARCHAR(), nullable=False))
    op.add_column('learning_interventions', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('learning_interventions', sa.Column('reliability_snapshot', sqlite.JSON(), nullable=True))
    op.add_column('job_execution_registry', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_attempts_is_deleted'), table_name='attempts')
    op.drop_column('attempts', 'deleted_at')
    op.drop_column('attempts', 'is_deleted')
    op.drop_column('attempts', 'updated_by')
    op.drop_column('attempts', 'created_by')
    op.drop_column('attempts', 'updated_at')
    op.drop_column('attempts', 'created_at')
    # ### end Alembic commands ###
