"""add_question_authoring_and_revision_queue

Revision ID: 4db43a970cab
Revises: bd3e1ee4ba10
Create Date: 2026-05-13 18:22:26.806905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db43a970cab'
down_revision: Union[str, None] = 'bd3e1ee4ba10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type if not exists (Postgres specific)
    workflow_status = postgresql.ENUM('DRAFT', 'REVIEW', 'VERIFIED', 'PUBLISHED', 'ARCHIVED', name='workflowstatusenum')
    workflow_status.create(op.get_bind(), checkfirst=True)
    
    op.create_table('revision_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_queues_id'), 'revision_queues', ['id'], unique=False)
    op.create_index(op.f('ix_revision_queues_is_deleted'), 'revision_queues', ['is_deleted'], unique=False)
    op.add_column('questions', sa.Column('status', sa.String(), nullable=False, server_default='PUBLISHED'))
    op.add_column('questions', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('explanation_quality_score', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('is_outdated', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('questions', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=False, server_default='2026-05-13 18:00:00'))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default='2026-05-13 18:00:00'))
    op.add_column('questions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('questions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_questions_is_deleted'), 'questions', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'questions', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_is_deleted'), table_name='questions')
    op.drop_column('questions', 'deleted_at')
    op.drop_column('questions', 'is_deleted')
    op.drop_column('questions', 'updated_by')
    op.drop_column('questions', 'created_by')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'last_reviewed_at')
    op.drop_column('questions', 'is_outdated')
    op.drop_column('questions', 'explanation_quality_score')
    op.drop_column('questions', 'reviewer_id')
    op.drop_column('questions', 'status')
    op.drop_index(op.f('ix_revision_queues_is_deleted'), table_name='revision_queues')
    op.drop_index(op.f('ix_revision_queues_id'), table_name='revision_queues')
    op.drop_table('revision_queues')
    # ### end Alembic commands ###
