"""Add forensic_data to Report

Revision ID: 64afae94d021
Revises: ce88a5aa7844
Create Date: 2026-05-13 16:24:24.487922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64afae94d021'
down_revision: Union[str, None] = 'ce88a5aa7844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               existing_nullable=False)
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_question_number'), 'questions', ['question_number'], unique=False)
    op.add_column('reports', sa.Column('forensic_data', sa.JSON(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('reports', 'forensic_data')
    op.drop_index(op.f('ix_questions_question_number'), table_name='questions')
    op.drop_column('questions', 'question_number')
    op.alter_column('attempts', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
