"""Add forensic_data to Report

Revision ID: 64afae94d021
Revises: ce88a5aa7844
Create Date: 2026-05-13 16:24:24.487922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64afae94d021'
down_revision: Union[str, None] = 'ce88a5aa7844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column_name in {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    if not _has_column('questions', 'question_number'):
        op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=True))
        with op.batch_alter_table('questions') as batch_op:
            batch_op.create_index(batch_op.f('ix_questions_question_number'), ['question_number'], unique=False)
            
    if not _has_column('reports', 'forensic_data'):
        op.add_column('reports', sa.Column('forensic_data', sa.JSON(), nullable=True))
        
    if not _has_column('users', 'institution_id'):
        op.add_column('users', sa.Column('institution_id', sa.Integer(), sa.ForeignKey('institutions.id'), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('reports', 'forensic_data')
    op.alter_column('attempts', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
