"""Add forensic_data to Report

Revision ID: 64afae94d021
Revises: ce88a5aa7844
Create Date: 2026-05-13 16:24:24.487922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64afae94d021'
down_revision: Union[str, None] = 'ce88a5aa7844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column_name in {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    # Use raw SQL with IF NOT EXISTS for better reliability in production
    # 1. Update Enum types (Postgres enums are tricky, we'll use string conversion if needed or just skip if it works)
    # Actually, alter_column should be fine if types match, but let's be safe.
    
    # 2. Add question_number to questions
    op.execute('ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_number INTEGER')
    # Index creation if not exists is also tricky, we can use a DO block
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'ix_questions_question_number') THEN
                CREATE INDEX ix_questions_question_number ON questions (question_number);
            END IF;
        END $$;
    """)
    
    # 3. Add forensic_data to reports
    op.execute('ALTER TABLE reports ADD COLUMN IF NOT EXISTS forensic_data JSON')
    
    # 4. Add institution_id foreign key to users if not exists
    # We'll check if the column exists first
    op.execute('ALTER TABLE users ADD COLUMN IF NOT EXISTS institution_id INTEGER REFERENCES institutions(id)')
    
    # 5. Handle Enums (Skip for now as they are harder to do idempotently in raw SQL without DO blocks)
    # The existing alter_column calls were mostly working or failing gracefully.
    try:
        op.alter_column('attempts', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
                   existing_nullable=False)
    except Exception:
        pass
        
    try:
        op.alter_column('users', 'role',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
                   existing_nullable=False)
    except Exception:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('reports', 'forensic_data')
    op.alter_column('attempts', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
