"""Phase 33 integrated

Revision ID: 6a54c4d280dd
Revises: 757a11800717
Create Date: 2026-05-12 22:32:45.825348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a54c4d280dd'
down_revision: Union[str, None] = '757a11800717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('attempts', 'status',
    #            existing_type=sa.VARCHAR(length=11),
    #            type_=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
    #            existing_nullable=False)
    op.add_column('users', sa.Column('flourishing_profile', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('sovereignty_overrides', sa.JSON(), nullable=True))
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(length=7),
    #            type_=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
    #            existing_nullable=False)
    # op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.alter_column('users', 'role',
    #            existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
    #            type_=sa.VARCHAR(length=7),
    #            existing_nullable=False)
    op.drop_column('users', 'sovereignty_overrides')
    op.drop_column('users', 'flourishing_profile')
    # op.alter_column('attempts', 'status',
    #            existing_type=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
    #            type_=sa.VARCHAR(length=11),
    #            existing_nullable=False)
    # ### end Alembic commands ###
