"""Sync schema

Revision ID: 757a11800717
Revises: ff64f4eededb
Create Date: 2026-05-12 22:18:58.390364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757a11800717'
down_revision: Union[str, None] = 'ff64f4eededb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    op.create_table('causal_inferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('estimate', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('evidence_support', sa.Float(), nullable=True),
    sa.Column('confounders', sa.JSON(), nullable=True),
    sa.Column('reasoning_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causal_inferences_id'), 'causal_inferences', ['id'], unique=False)
    op.create_index(op.f('ix_causal_inferences_target_id'), 'causal_inferences', ['target_id'], unique=False)
    op.create_index(op.f('ix_causal_inferences_target_type'), 'causal_inferences', ['target_type'], unique=False)
    op.create_table('cultural_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('governance_rules', sa.JSON(), nullable=True),
    sa.Column('pedagogical_patterns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultural_contexts_id'), 'cultural_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_cultural_contexts_name'), 'cultural_contexts', ['name'], unique=True)
    op.create_table('educational_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=True),
    sa.Column('resolution_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_escalations_id'), 'educational_escalations', ['id'], unique=False)
    op.create_index(op.f('ix_educational_escalations_target_id'), 'educational_escalations', ['target_id'], unique=False)
    op.create_index(op.f('ix_educational_escalations_type'), 'educational_escalations', ['type'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=True)
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_cohorts_name'), 'cohorts', ['name'], unique=False)
    op.create_table('knowledge_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_concepts_id'), 'knowledge_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_name'), 'knowledge_concepts', ['name'], unique=False)
    op.create_table('cohort_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_memberships_id'), 'cohort_memberships', ['id'], unique=False)
    op.create_table('educational_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', name='reviewstatusenum'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('override_payload', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_reviews_id'), 'educational_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_educational_reviews_target_id'), 'educational_reviews', ['target_id'], unique=False)
    op.create_index(op.f('ix_educational_reviews_target_type'), 'educational_reviews', ['target_type'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('evidence_quality', sa.Float(), nullable=True),
    sa.Column('durability', sa.Float(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_concepts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_edge_type'), 'knowledge_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_id'), 'knowledge_edges', ['id'], unique=False)
    op.create_table('qualitative_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualitative_signals_id'), 'qualitative_signals', ['id'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_signal_type'), 'qualitative_signals', ['signal_type'], unique=False)
    op.create_table('reality_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('divergence_score', sa.Float(), nullable=False),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('reconciliation_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reality_audits_id'), 'reality_audits', ['id'], unique=False)
    op.create_index(op.f('ix_reality_audits_target_id'), 'reality_audits', ['target_id'], unique=False)
    op.create_index(op.f('ix_reality_audits_target_type'), 'reality_audits', ['target_type'], unique=False)
    op.create_index(op.f('ix_attempt_answers_is_skipped'), 'attempt_answers', ['is_skipped'], unique=False)
    op.create_index(op.f('ix_attempt_answers_marked_for_review'), 'attempt_answers', ['marked_for_review'], unique=False)
    op.drop_index(op.f('ix_cognitive_snapshots_attempt_id'), table_name='cognitive_snapshots')
    op.create_index(op.f('ix_cognitive_snapshots_attempt_id'), 'cognitive_snapshots', ['attempt_id'], unique=True)
    op.add_column('learning_interventions', sa.Column('risk_level', sa.String(), nullable=True, server_default='STABLE'))
    op.add_column('learning_interventions', sa.Column('approval_status', sa.String(), nullable=True, server_default='AUTO_APPROVED'))
    op.drop_index(op.f('ix_learning_interventions_recommendation_id'), table_name='learning_interventions')
    op.create_index(op.f('ix_learning_interventions_recommendation_id'), 'learning_interventions', ['recommendation_id'], unique=True)
    op.add_column('users', sa.Column('institution_id', sa.Integer(), nullable=True))
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(length=7),
    #            type_=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
    #            existing_nullable=False)
    # op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.alter_column('users', 'role',
    #            existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
    #            type_=sa.VARCHAR(length=7),
    #            existing_nullable=False)
    op.drop_column('users', 'institution_id')
    op.drop_index(op.f('ix_learning_interventions_recommendation_id'), table_name='learning_interventions')
    op.create_index(op.f('ix_learning_interventions_recommendation_id'), 'learning_interventions', ['recommendation_id'], unique=False)
    op.drop_column('learning_interventions', 'approval_status')
    op.drop_column('learning_interventions', 'risk_level')
    op.drop_index(op.f('ix_cognitive_snapshots_attempt_id'), table_name='cognitive_snapshots')
    op.create_index(op.f('ix_cognitive_snapshots_attempt_id'), 'cognitive_snapshots', ['attempt_id'], unique=False)
    op.drop_index(op.f('ix_attempt_answers_marked_for_review'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_is_skipped'), table_name='attempt_answers')
    op.drop_index(op.f('ix_reality_audits_target_type'), table_name='reality_audits')
    op.drop_index(op.f('ix_reality_audits_target_id'), table_name='reality_audits')
    op.drop_index(op.f('ix_reality_audits_id'), table_name='reality_audits')
    op.drop_table('reality_audits')
    op.drop_index(op.f('ix_qualitative_signals_signal_type'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_id'), table_name='qualitative_signals')
    op.drop_table('qualitative_signals')
    op.drop_index(op.f('ix_knowledge_edges_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_edge_type'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_educational_reviews_target_type'), table_name='educational_reviews')
    op.drop_index(op.f('ix_educational_reviews_target_id'), table_name='educational_reviews')
    op.drop_index(op.f('ix_educational_reviews_id'), table_name='educational_reviews')
    op.drop_table('educational_reviews')
    op.drop_index(op.f('ix_cohort_memberships_id'), table_name='cohort_memberships')
    op.drop_table('cohort_memberships')
    op.drop_index(op.f('ix_knowledge_concepts_name'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_id'), table_name='knowledge_concepts')
    op.drop_table('knowledge_concepts')
    op.drop_index(op.f('ix_cohorts_name'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_educational_escalations_type'), table_name='educational_escalations')
    op.drop_index(op.f('ix_educational_escalations_target_id'), table_name='educational_escalations')
    op.drop_index(op.f('ix_educational_escalations_id'), table_name='educational_escalations')
    op.drop_table('educational_escalations')
    op.drop_index(op.f('ix_cultural_contexts_name'), table_name='cultural_contexts')
    op.drop_index(op.f('ix_cultural_contexts_id'), table_name='cultural_contexts')
    op.drop_table('cultural_contexts')
    op.drop_index(op.f('ix_causal_inferences_target_type'), table_name='causal_inferences')
    op.drop_index(op.f('ix_causal_inferences_target_id'), table_name='causal_inferences')
    op.drop_index(op.f('ix_causal_inferences_id'), table_name='causal_inferences')
    op.drop_table('causal_inferences')
    # ### end Alembic commands ###
