"""Add report versioning and job registry

Revision ID: 7f9633e90c49
Revises: e8b7bfcab8da
Create Date: 2026-05-13 17:59:58.772959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9633e90c49'
down_revision: Union[str, None] = 'e8b7bfcab8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_execution_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('error_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_execution_registry_id'), 'job_execution_registry', ['id'], unique=False)
    op.create_index(op.f('ix_job_execution_registry_job_name'), 'job_execution_registry', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_execution_registry_job_type'), 'job_execution_registry', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_execution_registry_reference_id'), 'job_execution_registry', ['reference_id'], unique=False)
    op.create_index(op.f('ix_job_execution_registry_status'), 'job_execution_registry', ['status'], unique=False)
    op.create_table('operational_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_metrics_id'), 'operational_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_operational_metrics_metric_type'), 'operational_metrics', ['metric_type'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.create_table('execution_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('parent_trace_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_traces_created_at'), 'execution_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_traces_function_name'), 'execution_traces', ['function_name'], unique=False)
    op.create_index(op.f('ix_execution_traces_id'), 'execution_traces', ['id'], unique=False)
    op.create_index(op.f('ix_execution_traces_module_name'), 'execution_traces', ['module_name'], unique=False)
    op.create_index(op.f('ix_execution_traces_parent_trace_id'), 'execution_traces', ['parent_trace_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_status'), 'execution_traces', ['status'], unique=False)
    op.create_index(op.f('ix_execution_traces_trace_id'), 'execution_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    with op.batch_alter_table('attempts') as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               existing_nullable=False)
    op.add_column('questions', sa.Column('statements_en', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('statements_hi', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('structure_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('options_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('integrity_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_questions_options_hash'), 'questions', ['options_hash'], unique=False)
    op.create_index(op.f('ix_questions_structure_hash'), 'questions', ['structure_hash'], unique=False)
    op.add_column('reports', sa.Column('reliability_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('forensic_audit_log', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('snapshot_bundle', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('report_version', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('rendering_version', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('evaluation_version', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('telemetry_version', sa.String(), nullable=False))
    op.drop_column('tests', 'created_at')
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               existing_nullable=False)
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_foreign_key('fk_users_institution_id', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_institution_id', type_='foreignkey')
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'STUDENT', 'EDUCATOR', name='roleenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.add_column('tests', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('reports', 'telemetry_version')
    op.drop_column('reports', 'evaluation_version')
    op.drop_column('reports', 'rendering_version')
    op.drop_column('reports', 'report_version')
    op.drop_column('reports', 'snapshot_bundle')
    op.drop_column('reports', 'forensic_audit_log')
    op.drop_column('reports', 'reliability_score')
    op.drop_index(op.f('ix_questions_structure_hash'), table_name='questions')
    op.drop_index(op.f('ix_questions_options_hash'), table_name='questions')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_column('questions', 'integrity_metadata')
    op.drop_column('questions', 'options_hash')
    op.drop_column('questions', 'structure_hash')
    op.drop_column('questions', 'content_hash')
    op.drop_column('questions', 'statements_hi')
    op.drop_column('questions', 'statements_en')
    with op.batch_alter_table('attempts') as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SOVEREIGNTY_PROTECTED', name='attemptstatusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_execution_traces_trace_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_status'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_parent_trace_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_module_name'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_function_name'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_created_at'), table_name='execution_traces')
    op.drop_table('execution_traces')
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_operational_metrics_metric_type'), table_name='operational_metrics')
    op.drop_index(op.f('ix_operational_metrics_id'), table_name='operational_metrics')
    op.drop_table('operational_metrics')
    op.drop_index(op.f('ix_job_execution_registry_status'), table_name='job_execution_registry')
    op.drop_index(op.f('ix_job_execution_registry_reference_id'), table_name='job_execution_registry')
    op.drop_index(op.f('ix_job_execution_registry_job_type'), table_name='job_execution_registry')
    op.drop_index(op.f('ix_job_execution_registry_job_name'), table_name='job_execution_registry')
    op.drop_index(op.f('ix_job_execution_registry_id'), table_name='job_execution_registry')
    op.drop_table('job_execution_registry')
    # ### end Alembic commands ###
