"""Add governance mixins to learning and cognitive models

Revision ID: bd3e1ee4ba10
Revises: 1a6510b47dd9
Create Date: 2026-05-13 18:18:37.789122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3e1ee4ba10'
down_revision: Union[str, None] = '1a6510b47dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cognitive_snapshots', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('cognitive_snapshots', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('cognitive_snapshots', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('cognitive_snapshots', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('cognitive_snapshots', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cognitive_snapshots_is_deleted'), 'cognitive_snapshots', ['is_deleted'], unique=False)
    op.add_column('learning_interventions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('learning_interventions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('learning_interventions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('learning_interventions', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('learning_interventions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('learning_interventions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_learning_interventions_is_deleted'), 'learning_interventions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_interventions_is_deleted'), table_name='learning_interventions')
    op.drop_column('learning_interventions', 'deleted_at')
    op.drop_column('learning_interventions', 'is_deleted')
    op.drop_column('learning_interventions', 'updated_by')
    op.drop_column('learning_interventions', 'created_by')
    op.drop_column('learning_interventions', 'updated_at')
    op.drop_column('learning_interventions', 'created_at')
    op.drop_index(op.f('ix_cognitive_snapshots_is_deleted'), table_name='cognitive_snapshots')
    op.drop_column('cognitive_snapshots', 'deleted_at')
    op.drop_column('cognitive_snapshots', 'is_deleted')
    op.drop_column('cognitive_snapshots', 'updated_by')
    op.drop_column('cognitive_snapshots', 'created_by')
    op.drop_column('cognitive_snapshots', 'updated_at')
    # ### end Alembic commands ###
