"""Add forensic metrics to Report

Revision ID: dbdacf5ea416
Revises: 4db43a970cab
Create Date: 2026-05-13 18:45:10.888788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdacf5ea416'
down_revision: Union[str, None] = '4db43a970cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('attempts', sa.Column('is_simulation', sa.Boolean(), nullable=True))
    with op.batch_alter_table('questions', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('bilingual_alignment_score', sa.Float(), nullable=True))
        # batch_op.add_column(sa.Column('is_current_affairs', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('content_date', sa.DateTime(), nullable=True))
        # batch_op.add_column(sa.Column('quality_notes', sa.JSON(), nullable=True))
        batch_op.alter_column('is_outdated',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text("'0'"))
        # batch_op.create_index(batch_op.f('ix_questions_is_deleted'), ['is_deleted'], unique=False)
        # batch_op.create_foreign_key('fk_questions_reviewer', 'users', ['reviewer_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mastery_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('negative_marks', sa.Float(), nullable=True))

    with op.batch_alter_table('revision_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('forgetting_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decay_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_overconfident', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('retention_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision_queues', 'retention_history')
    op.drop_column('revision_queues', 'is_overconfident')
    op.drop_column('revision_queues', 'decay_rate')
    op.drop_column('revision_queues', 'forgetting_count')
    op.drop_column('revision_queues', 'category')
    op.drop_column('reports', 'negative_marks')
    op.drop_column('reports', 'score_percentage')
    op.drop_column('reports', 'mastery_percentage')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_is_deleted'), table_name='questions')
    op.alter_column('questions', 'is_outdated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('questions', 'quality_notes')
    op.drop_column('questions', 'content_date')
    op.drop_column('questions', 'is_current_affairs')
    op.drop_column('questions', 'bilingual_alignment_score')
    op.drop_column('attempts', 'is_simulation')
    # ### end Alembic commands ###
