"""add optional subjects platform tables

Revision ID: e93f3dcfde5b
Revises: c40f1d2a9b76
Create Date: 2026-06-18 15:27:06.032925

Creates all UPSC Optional Subjects Platform tables (the ``optional_*``
namespace) from spec tasks 2.1 and 2.2:

  Content/syllabus domain: optional_subjects, optional_papers,
  optional_sections, optional_syllabus_nodes, optional_content_units,
  optional_diagrams, optional_source_refs, optional_pyqs,
  optional_hidden_topics.

  Student-activity domain: optional_subject_selections,
  optional_answer_attempts, optional_evaluation_reports,
  optional_video_segments, optional_concept_points, optional_recall_sessions,
  optional_recall_turns, optional_progress_events, optional_coverage.

Isolation (Requirement 2 / design Property 9): this migration ONLY creates the
``optional_*`` tables. It does NOT alter, drop, or recreate any existing
(non-``optional_``) table — in particular nothing related to GS Geography or
the existing MCQ domain. The autogenerate diff for pre-existing drift on the
``questions`` table was intentionally excluded from this migration.

Requirements: 15.1, 2.2
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93f3dcfde5b'
down_revision: Union[str, None] = 'c40f1d2a9b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optional_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completeness_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_subjects_id'), 'optional_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_optional_subjects_name'), 'optional_subjects', ['name'], unique=False)
    op.create_index(op.f('ix_optional_subjects_slug'), 'optional_subjects', ['slug'], unique=True)
    op.create_table('optional_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('PAPER_I', 'PAPER_II', name='paperlabelenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_papers_id'), 'optional_papers', ['id'], unique=False)
    op.create_index(op.f('ix_optional_papers_subject_id'), 'optional_papers', ['subject_id'], unique=False)
    op.create_table('optional_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('covered_weight', sa.Float(), nullable=False),
    sa.Column('covered_percent', sa.Float(), nullable=False),
    sa.Column('remaining_percent', sa.Float(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', name='uq_optional_coverage_student_subject')
    )
    op.create_index(op.f('ix_optional_coverage_id'), 'optional_coverage', ['id'], unique=False)
    op.create_index(op.f('ix_optional_coverage_student_id'), 'optional_coverage', ['student_id'], unique=False)
    op.create_index(op.f('ix_optional_coverage_subject_id'), 'optional_coverage', ['subject_id'], unique=False)
    op.create_table('optional_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('SECTION_A', 'SECTION_B', name='sectionlabelenum'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['optional_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_sections_id'), 'optional_sections', ['id'], unique=False)
    op.create_index(op.f('ix_optional_sections_paper_id'), 'optional_sections', ['paper_id'], unique=False)
    op.create_table('optional_subject_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_subject_selections_id'), 'optional_subject_selections', ['id'], unique=False)
    op.create_index(op.f('ix_optional_subject_selections_is_active'), 'optional_subject_selections', ['is_active'], unique=False)
    op.create_index(op.f('ix_optional_subject_selections_student_id'), 'optional_subject_selections', ['student_id'], unique=False)
    op.create_index(op.f('ix_optional_subject_selections_subject_id'), 'optional_subject_selections', ['subject_id'], unique=False)
    op.create_table('optional_syllabus_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('official_phrasing', sa.Text(), nullable=True),
    sa.Column('node_type', sa.Enum('PAPER', 'SECTION', 'TOPIC', 'SUBTOPIC', name='syllabusnodetypeenum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'IN_REVIEW', 'REVIEWED', name='optionalreviewstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['optional_syllabus_nodes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['optional_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_syllabus_nodes_id'), 'optional_syllabus_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_optional_syllabus_nodes_parent_id'), 'optional_syllabus_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_optional_syllabus_nodes_section_id'), 'optional_syllabus_nodes', ['section_id'], unique=False)
    op.create_table('optional_content_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_node_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('exam_keywords', sa.JSON(), nullable=True),
    sa.Column('answer_language', sa.JSON(), nullable=True),
    sa.Column('hidden_topics', sa.JSON(), nullable=True),
    sa.Column('authored', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'IN_REVIEW', 'REVIEWED', name='optionalreviewstatusenum'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['syllabus_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_content_units_id'), 'optional_content_units', ['id'], unique=False)
    op.create_index(op.f('ix_optional_content_units_is_deleted'), 'optional_content_units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_optional_content_units_review_status'), 'optional_content_units', ['review_status'], unique=False)
    op.create_index(op.f('ix_optional_content_units_syllabus_node_id'), 'optional_content_units', ['syllabus_node_id'], unique=False)
    op.create_table('optional_progress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('syllabus_node_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('READ_COMPLETE', 'PRACTICE_PASS', 'RECALL_THRESHOLD', name='progresseventtypeenum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.ForeignKeyConstraint(['syllabus_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_progress_events_event_type'), 'optional_progress_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_optional_progress_events_id'), 'optional_progress_events', ['id'], unique=False)
    op.create_index(op.f('ix_optional_progress_events_student_id'), 'optional_progress_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_optional_progress_events_subject_id'), 'optional_progress_events', ['subject_id'], unique=False)
    op.create_index(op.f('ix_optional_progress_events_syllabus_node_id'), 'optional_progress_events', ['syllabus_node_id'], unique=False)
    op.create_table('optional_video_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_node_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('video_ref', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_video_segments_id'), 'optional_video_segments', ['id'], unique=False)
    op.create_index(op.f('ix_optional_video_segments_segment_order'), 'optional_video_segments', ['segment_order'], unique=False)
    op.create_index(op.f('ix_optional_video_segments_subject_id'), 'optional_video_segments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_optional_video_segments_topic_node_id'), 'optional_video_segments', ['topic_node_id'], unique=False)
    op.create_table('optional_concept_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_segment_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_segment_id'], ['optional_video_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_concept_points_id'), 'optional_concept_points', ['id'], unique=False)
    op.create_index(op.f('ix_optional_concept_points_video_segment_id'), 'optional_concept_points', ['video_segment_id'], unique=False)
    op.create_table('optional_diagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_unit_id', sa.Integer(), nullable=True),
    sa.Column('diagram_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_unit_id'], ['optional_content_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_diagrams_content_unit_id'), 'optional_diagrams', ['content_unit_id'], unique=False)
    op.create_index(op.f('ix_optional_diagrams_diagram_id'), 'optional_diagrams', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_optional_diagrams_id'), 'optional_diagrams', ['id'], unique=False)
    op.create_table('optional_recall_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('video_segment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='recallsessionstatusenum'), nullable=False),
    sa.Column('recall_score', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_segment_id'], ['optional_video_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_recall_sessions_id'), 'optional_recall_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_optional_recall_sessions_status'), 'optional_recall_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_optional_recall_sessions_student_id'), 'optional_recall_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_optional_recall_sessions_video_segment_id'), 'optional_recall_sessions', ['video_segment_id'], unique=False)
    op.create_table('optional_source_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_unit_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_unit_id'], ['optional_content_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_source_refs_content_unit_id'), 'optional_source_refs', ['content_unit_id'], unique=False)
    op.create_index(op.f('ix_optional_source_refs_id'), 'optional_source_refs', ['id'], unique=False)
    op.create_table('optional_hidden_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_node_id', sa.Integer(), nullable=False),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_ref_id'], ['optional_source_refs.id'], ),
    sa.ForeignKeyConstraint(['syllabus_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_hidden_topics_id'), 'optional_hidden_topics', ['id'], unique=False)
    op.create_index(op.f('ix_optional_hidden_topics_source_ref_id'), 'optional_hidden_topics', ['source_ref_id'], unique=False)
    op.create_index(op.f('ix_optional_hidden_topics_syllabus_node_id'), 'optional_hidden_topics', ['syllabus_node_id'], unique=False)
    op.create_table('optional_pyqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('topic_node_id', sa.Integer(), nullable=True),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('paper_label', sa.Enum('PAPER_I', 'PAPER_II', name='paperlabelenum'), nullable=True),
    sa.Column('section_label', sa.Enum('SECTION_A', 'SECTION_B', name='sectionlabelenum'), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('beyond_syllabus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['optional_papers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['optional_sections.id'], ),
    sa.ForeignKeyConstraint(['source_ref_id'], ['optional_source_refs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_pyqs_beyond_syllabus'), 'optional_pyqs', ['beyond_syllabus'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_id'), 'optional_pyqs', ['id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_is_deleted'), 'optional_pyqs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_paper_id'), 'optional_pyqs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_paper_label'), 'optional_pyqs', ['paper_label'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_section_id'), 'optional_pyqs', ['section_id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_section_label'), 'optional_pyqs', ['section_label'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_source_ref_id'), 'optional_pyqs', ['source_ref_id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_subject_id'), 'optional_pyqs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_topic_node_id'), 'optional_pyqs', ['topic_node_id'], unique=False)
    op.create_index(op.f('ix_optional_pyqs_year'), 'optional_pyqs', ['year'], unique=False)
    op.create_table('optional_recall_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('audio_ref', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('matched_concepts', sa.JSON(), nullable=False),
    sa.Column('missed_concepts', sa.JSON(), nullable=False),
    sa.Column('recall_score', sa.Float(), nullable=False),
    sa.Column('hint_given', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['optional_recall_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_recall_turns_id'), 'optional_recall_turns', ['id'], unique=False)
    op.create_index(op.f('ix_optional_recall_turns_session_id'), 'optional_recall_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_optional_recall_turns_turn_order'), 'optional_recall_turns', ['turn_order'], unique=False)
    op.create_table('optional_answer_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_node_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('TYPED', 'SPOKEN', 'HANDWRITTEN', name='answermodeenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'EVALUATED', 'FAILED', name='answerattemptstatusenum'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('pyq_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('conclusion_text', sa.Text(), nullable=True),
    sa.Column('source_media_ref', sa.String(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pyq_id'], ['optional_pyqs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['optional_subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_node_id'], ['optional_syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_answer_attempts_id'), 'optional_answer_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_is_deleted'), 'optional_answer_attempts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_pyq_id'), 'optional_answer_attempts', ['pyq_id'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_status'), 'optional_answer_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_student_id'), 'optional_answer_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_subject_id'), 'optional_answer_attempts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_optional_answer_attempts_topic_node_id'), 'optional_answer_attempts', ['topic_node_id'], unique=False)
    op.create_table('optional_evaluation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('incomplete_sections', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['optional_answer_attempts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optional_evaluation_reports_attempt_id'), 'optional_evaluation_reports', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_optional_evaluation_reports_id'), 'optional_evaluation_reports', ['id'], unique=False)
    op.create_index(op.f('ix_optional_evaluation_reports_student_id'), 'optional_evaluation_reports', ['student_id'], unique=False)

    # Partial unique index enforcing "one active selection per student"
    # (design SubjectSelection note / R1.3). History rows (is_active=False) are
    # retained for audit; only one active selection may exist per student.
    # Expressed per-dialect so it applies on both SQLite (dev) and Postgres.
    op.create_index(
        "uq_optional_active_selection_per_student",
        "optional_subject_selections",
        ["student_id"],
        unique=True,
        sqlite_where=sa.text("is_active = 1"),
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_optional_active_selection_per_student", table_name="optional_subject_selections")
    op.drop_index(op.f('ix_optional_evaluation_reports_student_id'), table_name='optional_evaluation_reports')
    op.drop_index(op.f('ix_optional_evaluation_reports_id'), table_name='optional_evaluation_reports')
    op.drop_index(op.f('ix_optional_evaluation_reports_attempt_id'), table_name='optional_evaluation_reports')
    op.drop_table('optional_evaluation_reports')
    op.drop_index(op.f('ix_optional_answer_attempts_topic_node_id'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_subject_id'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_student_id'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_status'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_pyq_id'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_is_deleted'), table_name='optional_answer_attempts')
    op.drop_index(op.f('ix_optional_answer_attempts_id'), table_name='optional_answer_attempts')
    op.drop_table('optional_answer_attempts')
    op.drop_index(op.f('ix_optional_recall_turns_turn_order'), table_name='optional_recall_turns')
    op.drop_index(op.f('ix_optional_recall_turns_session_id'), table_name='optional_recall_turns')
    op.drop_index(op.f('ix_optional_recall_turns_id'), table_name='optional_recall_turns')
    op.drop_table('optional_recall_turns')
    op.drop_index(op.f('ix_optional_pyqs_year'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_topic_node_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_subject_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_source_ref_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_section_label'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_section_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_paper_label'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_paper_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_is_deleted'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_id'), table_name='optional_pyqs')
    op.drop_index(op.f('ix_optional_pyqs_beyond_syllabus'), table_name='optional_pyqs')
    op.drop_table('optional_pyqs')
    op.drop_index(op.f('ix_optional_hidden_topics_syllabus_node_id'), table_name='optional_hidden_topics')
    op.drop_index(op.f('ix_optional_hidden_topics_source_ref_id'), table_name='optional_hidden_topics')
    op.drop_index(op.f('ix_optional_hidden_topics_id'), table_name='optional_hidden_topics')
    op.drop_table('optional_hidden_topics')
    op.drop_index(op.f('ix_optional_source_refs_id'), table_name='optional_source_refs')
    op.drop_index(op.f('ix_optional_source_refs_content_unit_id'), table_name='optional_source_refs')
    op.drop_table('optional_source_refs')
    op.drop_index(op.f('ix_optional_recall_sessions_video_segment_id'), table_name='optional_recall_sessions')
    op.drop_index(op.f('ix_optional_recall_sessions_student_id'), table_name='optional_recall_sessions')
    op.drop_index(op.f('ix_optional_recall_sessions_status'), table_name='optional_recall_sessions')
    op.drop_index(op.f('ix_optional_recall_sessions_id'), table_name='optional_recall_sessions')
    op.drop_table('optional_recall_sessions')
    op.drop_index(op.f('ix_optional_diagrams_id'), table_name='optional_diagrams')
    op.drop_index(op.f('ix_optional_diagrams_diagram_id'), table_name='optional_diagrams')
    op.drop_index(op.f('ix_optional_diagrams_content_unit_id'), table_name='optional_diagrams')
    op.drop_table('optional_diagrams')
    op.drop_index(op.f('ix_optional_concept_points_video_segment_id'), table_name='optional_concept_points')
    op.drop_index(op.f('ix_optional_concept_points_id'), table_name='optional_concept_points')
    op.drop_table('optional_concept_points')
    op.drop_index(op.f('ix_optional_video_segments_topic_node_id'), table_name='optional_video_segments')
    op.drop_index(op.f('ix_optional_video_segments_subject_id'), table_name='optional_video_segments')
    op.drop_index(op.f('ix_optional_video_segments_segment_order'), table_name='optional_video_segments')
    op.drop_index(op.f('ix_optional_video_segments_id'), table_name='optional_video_segments')
    op.drop_table('optional_video_segments')
    op.drop_index(op.f('ix_optional_progress_events_syllabus_node_id'), table_name='optional_progress_events')
    op.drop_index(op.f('ix_optional_progress_events_subject_id'), table_name='optional_progress_events')
    op.drop_index(op.f('ix_optional_progress_events_student_id'), table_name='optional_progress_events')
    op.drop_index(op.f('ix_optional_progress_events_id'), table_name='optional_progress_events')
    op.drop_index(op.f('ix_optional_progress_events_event_type'), table_name='optional_progress_events')
    op.drop_table('optional_progress_events')
    op.drop_index(op.f('ix_optional_content_units_syllabus_node_id'), table_name='optional_content_units')
    op.drop_index(op.f('ix_optional_content_units_review_status'), table_name='optional_content_units')
    op.drop_index(op.f('ix_optional_content_units_is_deleted'), table_name='optional_content_units')
    op.drop_index(op.f('ix_optional_content_units_id'), table_name='optional_content_units')
    op.drop_table('optional_content_units')
    op.drop_index(op.f('ix_optional_syllabus_nodes_section_id'), table_name='optional_syllabus_nodes')
    op.drop_index(op.f('ix_optional_syllabus_nodes_parent_id'), table_name='optional_syllabus_nodes')
    op.drop_index(op.f('ix_optional_syllabus_nodes_id'), table_name='optional_syllabus_nodes')
    op.drop_table('optional_syllabus_nodes')
    op.drop_index(op.f('ix_optional_subject_selections_subject_id'), table_name='optional_subject_selections')
    op.drop_index(op.f('ix_optional_subject_selections_student_id'), table_name='optional_subject_selections')
    op.drop_index(op.f('ix_optional_subject_selections_is_active'), table_name='optional_subject_selections')
    op.drop_index(op.f('ix_optional_subject_selections_id'), table_name='optional_subject_selections')
    op.drop_table('optional_subject_selections')
    op.drop_index(op.f('ix_optional_sections_paper_id'), table_name='optional_sections')
    op.drop_index(op.f('ix_optional_sections_id'), table_name='optional_sections')
    op.drop_table('optional_sections')
    op.drop_index(op.f('ix_optional_coverage_subject_id'), table_name='optional_coverage')
    op.drop_index(op.f('ix_optional_coverage_student_id'), table_name='optional_coverage')
    op.drop_index(op.f('ix_optional_coverage_id'), table_name='optional_coverage')
    op.drop_table('optional_coverage')
    op.drop_index(op.f('ix_optional_papers_subject_id'), table_name='optional_papers')
    op.drop_index(op.f('ix_optional_papers_id'), table_name='optional_papers')
    op.drop_table('optional_papers')
    op.drop_index(op.f('ix_optional_subjects_slug'), table_name='optional_subjects')
    op.drop_index(op.f('ix_optional_subjects_name'), table_name='optional_subjects')
    op.drop_index(op.f('ix_optional_subjects_id'), table_name='optional_subjects')
    op.drop_table('optional_subjects')
    # ### end Alembic commands ###
